# Generated by Django 4.1.3 on 2022-11-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='gallery')),
                ('fistName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
