# Generated by Django 4.1.3 on 2022-11-11 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_fistname_image_firstname_alter_image_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Gallery',
        ),
    ]
