# Generated by Django 4.1.3 on 2022-11-14 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_image_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='identify')),
            ],
        ),
    ]
